version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=3020
    ports:
      - '3020:3020'
    volumes:
      - ./src:/app/src