version: '3'

services:
  database:
    image: 'mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-20.04'
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!